### ISSUE TITLE
Improve navigation for docs

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks.org#107]
Once #106 is merged it would be good to add some secondary navigation within the docs section.

**Comment by SteelWagstaff** [comment]
I will write a draft PR which adds two top level nav items:
**user docs**
1. installation
2. debugging
3. Pressbooks SAML SSO
4. Pressbooks CAS SSO

**dev docs**

1. 1. local dev
2. 2. PHP storm config
3. [Coding Standards](https://docs.pressbooks.org/docs/coding-standards/)
4. [Unit Testing](https://docs.pressbooks.org/docs/unit-testing/)
5. [Workflow](https://docs.pressbooks.org/docs/workflow/)
6. [Theme Development](https://docs.pressbooks.org/docs/theme-development/)
7. [Rest API](https://docs.pressbooks.org/docs/rest-api/)

Also set up redirects in netlify.toml for any URLs that change. Assign to Ned when ready to build accessible drop down menus.

**Comment by greatislander** [comment]
Resolved in #110, I think?
